[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "functions/express"

[build]
  command = "echo building"
[dev]
  framework = "#custom"
  command = "sleep infinity"
  targetPort = 8888

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/express/:splat"