[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "functions/express"

[build]
  command = "echo building"
[dev]
  framework = "#custom"
  command = "echo dev"
  targetPort = 8888